#!/usr/bin/env bash
set -e
cd "$(readlink -f "$0" | xargs dirname)"/..

# pg_stat_activity
# pg_stat_all_indexes
# pg_stat_all_tables
# pg_stat_archiver
# pg_stat_bgwriter
# pg_stat_database
# pg_stat_database_conflicts
# pg_stat_progress_vacuum
# pg_stat_replication
# pg_stat_ssl
# pg_stat_sys_indexes
# pg_stat_sys_tables
# pg_stat_user_functions
# pg_stat_user_indexes
# pg_stat_user_tables
# pg_stat_wal_receiver
# pg_stat_xact_all_tables
# pg_stat_xact_sys_tables
# pg_stat_xact_user_functions
# pg_stat_xact_user_tables
# pg_statio_all_indexes
# pg_statio_all_sequences
# pg_statio_all_tables
# pg_statio_sys_indexes
# pg_statio_sys_sequences
# pg_statio_sys_tables
# pg_statio_user_indexes
# pg_statio_user_sequences
# pg_statio_user_tables
# pg_statistic
# pg_stats



watch -n 0.1 -d 'bin/bmo-psql --pset="pager=off" -f views/active-queries.sql'

# #-----------------------------------------------------------------------------------------------------------
# # clear
# while [ 1 ]; do
#   bin/bmo-psql --pset="pager=off" -c "select TIME.age_as_text( query_start ) as age, query from pg_stat_activity order by query_start;"
#   read -t 0.25 -n 1 key
#   if [[ $key = q ]]; then
#     clear
#     break
#     fi
#   done
